### ISSUE TITLE
Issue loading

### ISSUE THREAD

**Issue by red1134** [nitrog0d/DesktopCamera#1]
It spams the melon loader console with something like this
`at MelonLoader.Main.OnUpdate () [0x00068] in <1340ae9407f24122a5519a829bd6b386>:0
[04:37:36.611] [MelonLoader] [DesktopCamera] [Error] System.TypeLoadException: Failure has occurred while loading a type.`

**Comment by nitrog0d** [comment]
My guess is that you didn't install MelonLoader correctly, check this repository: https://github.com/Slaynash/MelonLoaderAutoInstaller
