### ISSUE TITLE
Dunno if this counts as priority rn but...

### ISSUE THREAD

**Issue by ItsMeZeppelin** [nitrog0d/DesktopCamera#10]
Observed that when I have the DesktopCamera out, gpu temperature suddenly rises up, playing vrc normally would take me to 50-60c but upon turning on DesktopCamera temps would slowly go up at a maximum of 85c (maybe its an issue with older gpus as mine is an old GTX 660 2gb but just making real)

**Comment by nitrog0d** [comment]
I must say bruh
