### ISSUE TITLE
VRChat did it again, as usual per update

### ISSUE THREAD

**Issue by ItsMeZeppelin** [nitrog0d/DesktopCamera#11]
[MelonLoader_20-07-17_05-33-39.728.log](https://github.com/nitrog0d/DesktopCamera/files/4934301/MelonLoader_20-07-17_05-33-39.728.log)
-Pressing pins button while camera is out will turn on a filter (Old Timey)
-Pressing none on filters crashes the game again
-Pressing any filters at all will cause this error
![image](https://user-images.githubusercontent.com/64414315/87725300-9b9b9f80-c7ef-11ea-8c65-acc5db593027.png)

[Will try to find a fix as well to help you with it <3]

**Comment by nitrog0d** [comment]
Updated, thank you <3
https://github.com/nitrog0d/DesktopCamera/releases
