### ISSUE TITLE
Broken on VRChat 2020.1.1p5 [Build 924]

### ISSUE THREAD

**Issue by ItsMeZeppelin** [nitrog0d/DesktopCamera#2]
![image](https://user-images.githubusercontent.com/64414315/81112524-5fc39e80-8f51-11ea-85f4-1c4d1b229afc.png)

[Keep making people happy with what you're doing! Don't overwork though as you need rest as well]

**Comment by nitrog0d** [comment]
I'll fix it soon, thanks for telling me!

**Comment by nitrog0d** [comment]
Fixed it, https://github.com/nitrog0d/DesktopCamera/releases
