### ISSUE TITLE
Melon updated to Unhollower version 0.3.1.0

### ISSUE THREAD

**Issue by ItsMeZeppelin** [nitrog0d/DesktopCamera#3]
There are no errors shown this time as it instantly crashes the game

[Work hard, but not too much, taking a break is a must as well❤]

**Comment by nitrog0d** [comment]
Thank you for notifying me again, I'll update when I wake up again

**Comment by nitrog0d** [comment]
Updated, https://github.com/nitrog0d/DesktopCamera/releases
