### ISSUE TITLE
VRChat 2020.2.1 Build 926, we really love vrc

### ISSUE THREAD

**Issue by ItsMeZeppelin** [nitrog0d/DesktopCamera#4]
![image](https://user-images.githubusercontent.com/64414315/81734348-efbf9600-94c5-11ea-9871-e53fe768ae63.png)
It may be the replacement button they added on the update, changing the extender button to a lock button.
[Again, do not overwork, do everything at your own pace. Much love❤]

**Comment by nitrog0d** [comment]
Yeah, I definitely love VRChat...
This one was more hard because they changed some stuff in the camera class, but it's released now.
https://github.com/nitrog0d/DesktopCamera/releases
