### ISSUE TITLE
I think I found an error

### ISSUE THREAD

**Issue by ItsMeZeppelin** [nitrog0d/DesktopCamera#5]
![image](https://user-images.githubusercontent.com/64414315/84234668-3638fc80-ab27-11ea-8d1e-4b69e1efb0de.png)
This happened when I changed from green screen to No filter
Error appeared and then game crashed
[Thank you for your hard work <3]

**Comment by nitrog0d** [comment]
Yeah I'm pretty sure filters are broken and I didn't have any motivation to fix it... I'm sorry... Personal problems
I'll see what I can do tomorrow, thanks for reporting!

**Comment by nitrog0d** [comment]
Sorry for the long wait... That's fixed for now but I'll see what I can do to avoid the same problem in the future incase VRChat updates.
https://github.com/nitrog0d/DesktopCamera/releases
